services:
  postgres:
    image: postgres
    hostname: postgres
    container_name: postgres
    command: -p 5432
    restart: on-failure
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - main
    expose:
      - '5432'
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data


  app:
    build: .
    container_name: nodejs
    depends_on:
      - postgres
    expose:
      - '3000'
    ports:
      - '3000:3000'
    networks:
      - main
    volumes:
      - .:/app/

  nginx:
    image: nginx
    hostname: nginx
    container_name: nginx
    command: sh -c "nginx -g 'daemon off;'"
    restart: on-failure
    depends_on:
      - app
      - postgres
    networks:
      - main
    expose:
      - "80"
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf


networks:
  main:

volumes:
  data: